// Code generated by "go run types_generate.go"; DO NOT EDIT.

package client

import "github.com/miekg/dns"

func (rr *TSIG) Header() *dns.RR_Header { return &rr.Hdr }

func (rr *TSIG) len() int {
	l := len(rr.Hdr.Name) + 1
	l += 10
	l += len(rr.Algorithm) + 1
	l += 6 // TimeSigned
	l += 2 // Fudge
	l += 2 // MACSize
	l += len(rr.MAC) / 2
	l += 2 // OrigId
	l += 2 // Error
	l += 2 // OtherLen
	l += len(rr.OtherData) / 2
	return l
}
